version: '3.3' # config syntax version of docker-compose
services:
  ansible:
    image: "ironbank-derived-ansible-runner:1.4.6_bb2"
    volumes:
    - $HOME/.ssh/homelab.ssh.privatekey:/runner/env/ssh_key:ro #Edit as needed
#    - $HOME/.ssh/target-machine.ssh.privatekey:/runner/env/ssh_key:ro #Edit as needed
    - ./shared_mount:/shared_mount:rw
#    - ./ansible-runner/artifacts:/runner/artifacts:rw
    - ./ansible-runner/env:/runner/env:rw
    - ./ansible-runner/inventory:/runner/inventory:rw
    - ./ansible-runner/project:/runner/project:rw
    - ./ansible-runner/ansible.cfg:/etc/ansible/ansible.cfg:ro
    environment:
      RUNNER_PLAYBOOK: /runner/project/deploy_harbor_registry.yml
