{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-all-jobservice
 namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: jobservice
      {{- include "harbor.matchLabels" $ | nindent 6 }}
  action: ALLOW
  rules:
    - {}
{{- end }}

