harbor:
  # -- Toggle deployment of harbor
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/harbor.git
    branch: $CI_COMMIT_BRANCH
    path: chart

  # -- Flux reconciliation overrides specifically for the Jaeger Package
  flux: {}

  # -- Redirect the package ingress to a specific Istio Gateway (listed in `istio.gateways`).  The default is "public".
  ingress:
    gateway: ""

  sso:
    # -- Toggle SSO for Harbor on and off
    enabled: false

    # -- OIDC Client ID to use for Harbor
    client_id: ""

    # -- OIDC Client Secret to use for Harbo
    client_secret: ""

  # -- Values to pass through to Habor chart: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/harbor.git
  values: {}

  # -- Post Renderers.  See docs/postrenders.md
  postRenderers: []

# For development
istio:
  ingressGateways:
    passthrough-ingressgateway:
      enabled: false
      type: "NodePort"

# Network Policies
networkPolicies:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckoperator:
  enabled: false
logging:
  enabled: false
fluentbit:
  enabled: false

# Monitoring
monitoring:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
