---
# Note: tag never just means the logic only run when you explicitly call the tag
- name: deploy_harbor_k3d_test_cluster
  hosts: harbor_k3d_test_node
  connection: ssh
  gather_facts: false
  environment:
    KUBECONFIG: "/shared_mount/harbor_registry_kubectl.config" #allows kubectl commands to work
  roles: 
  - role: deploy_harbor_k3d_test_cluster
    tags: ["deploy_harbor_k3d_test_cluster", "never"]

- name: deploy_harbor_registry
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    KUBECONFIG: "/shared_mount/harbor_registry_kubectl.config" #allows kubectl commands to work
  roles: 
  - role: deploy_harbor_registry
    tags: ["deploy_harbor", "never"]

- name: populate_harbor_registry
  hosts: harbor_k3d_test_node
  connection: ssh
  gather_facts: false
  environment:
    KUBECONFIG: "/home/{{REMOTE_VM_USER}}/.kube/config"
  roles: 
  - role: populate_harbor_registry
    tags: ["populate_harbor", "never"]

- name: deploy_bigbang_k3d_test_cluster
  hosts: bigbang_k3d_test_node
  connection: ssh
  gather_facts: false
  environment:
    KUBECONFIG: "/home/{{REMOTE_VM_USER}}/.kube/config" #k3d will create file specified in env var  
  roles: 
  - role: deploy_bigbang_k3d_test_cluster
    tags: ["deploy_bigbang_k3d_test_cluster", "never"]
