{{- if and .Values.bbtests.enabled (not .Values.expose.tls.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: ci-only
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- $ssCert := genSelfSignedCert "harbor.bb..dev" nil nil 30 }}
  tls.crt: {{ $ssCert.Cert  | b64enc | quote }}
  tls.key: {{ genPrivateKey "rsa" | b64enc | quote }}
{{- end }}
