{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ template "harbor.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels: {{ include "harbor.labels" . | nindent 4 }}
spec:
  gateways:
  {{- range .Values.istio.harbor.gateways }}
  - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.harbor.hosts }}
  - {{ tpl . $}}
  {{- end }}
  http:
  - name: core
    match:
    - uri:
        prefix: '/api/'
    - uri:
        prefix: '/c/'
    - uri:
        prefix: '/chartrepo/'
    - uri:
        prefix: '/service/'
    - uri:
        prefix: '/v2'
    route:
    - destination:
        host: {{ template "harbor.core" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
  - route:
    - destination:
        host: {{ template "harbor.portal" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
{{- end }}
