{{- if .Values.registry.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.registry.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.registry.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "harbor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "harbor.chart" . }}
{{- with .Values.registry.serviceAccount.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- if .Values.registry.serviceAccount.imagePullSecrets }}
  imagePullSecrets:
  {{- range .Values.registry.serviceAccount.imagePullSecrets }}
    - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
