apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.core" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- if not .Values.existingSecretSecretKey }}
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  {{- end }}
  secret: {{ .Values.core.secret | default (randAlphaNum 16) | b64enc | quote }}
  {{- if not .Values.core.secretName }}
  tls.crt: {{ (required "\"core.tokenCertificate\" is required when core.secretName is unset!" .Values.core.tokenCertificate) | b64enc }}
  tls.key: {{ (required "\"core.tokenKey\" is required when core.secretName is unset!" .Values.core.tokenKey) | b64enc }}
  {{- end }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  {{- if not .Values.postgresql.existingSecret }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
  {{- end }}
  {{- if not .Values.registry.credentials.existingSecret }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password | b64enc | quote }}
  {{- end }}
  CSRF_KEY: {{ .Values.core.xsrfKey | default (randAlphaNum 32) | b64enc | quote }}
  {{- template "harbor.traceJaegerPassword" . }}
